### ISSUE TITLE
Install fails with a build error

### ISSUE THREAD

**Issue by bassybeats** [billstron/passwordless-mysql#1]
I get the below install error. Any Idea why..?

> bcrypt@0.8.4 install /root/node_modules/passwordless-mysql/node_modules/bcrypt
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Linux 3.12.27-xenU
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/passwordless-mysql/node_modules/bcrypt
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Linux 3.12.27-xenU
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "passwordless-mysql" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by billstron** [comment]
What are you system details -- OS and Version?  It looks like you might not have `make` installed.

**Comment by knoxcard** [comment]
did you try the -g option?

npm install passwordless-mysql --save -g

**Comment by knoxcard** [comment]
Okay, this worked for me on my Linux (Production) environment

but not on

WIndows (Dev Environment)  - Windows 10 - WAMP

**Comment by billstron** [comment]
Honestly, I've never tested it on windows.  What error are you seeing?

**Comment by strictd** [comment]
Just ran into this issue on windows.. Upgrade library to use bcryptjs npm module. uses same compare / hash function and arguments. i'll put in a PR for it
